### ISSUE TITLE
Items that have different NBT cannot be sold together

### ISSUE THREAD

**Issue by Blackyvk** [Ghost-chu/QuickShop-Reremake#104]
NBT Tags are messing with some items, even if they have the same enchants and name, also some special potions from the brewery plugin, may be more difficult to fix i think.

I'll attach here an schematic file with an example of items, if you can test with them.

[chests.zip](https://github.com/Ghost-chu/QuickShop-Reremake/files/3269925/chests.zip)
Version: 1.13.2

**Comment by Ghost-chu** [comment]
Already added custom item matcher in #938 snapshot build.
You can find it in after #938 builds.

**Comment by Blackyvk** [comment]
Tested already, unless I didnt configure it properly, it didnt work... try with those items I put on the schematic.
```

matcher:
  item:
    damage: true
    displayname: true
    lores: true
    enchs: true
    potions: false
    attributes: false
    itemflags: false
    custommodeldata: false
```
