### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by yannicklamprecht** [Ghost-chu/QuickShop-Reremake#35]
Needs heavily refactoring
- be SOLID
    - [ ] Single Responsibility Principle
    - [x] Open Closed Principle
    - [x] Liskov Substitution Principle
    - [x] Interface Segregation Principle
    - [ ] Dependency Inversion Principle
- [ ] remove cyclic dependencies ( MsgUtil is depending on Util and the other way around, same for DatabaseHelper)
- [x] properly inject dependencies instead of static abuse shit
- [ ] properly handle configurations
- [x] write Adapter for used functionality in libraries
- [x] use PreparedStatement in the right way
- [x] cache data instead of writing each time -> persist every N minutes
- [x] encapsulate the classes to reduce complexity
- [x] cleanup commands, introduce a subcommand system
- [x] use Player#hasPermission instead of using an explicit PermissionProvider that is already injected into Bukkit system
- [x] remove duplication of ServerNMS and ItemNMS
- [ ] refactor MsgUtil
    - reduce code duplication
    - apply SRP

- [x] write javadoc for plugin
- [x] Remove classes that are not used anymore
- [x] refactor shop loader

**Comment by Ghost-chu** [comment]
`use Player#hasPermission instead of using an explicit PermissionProvider that is already injected into Bukkit system`
Actually this is from upstream `https://github.com/KaiKikuchi/QuickShop`'s code.
New code part already use hasPermission,

**Comment by yannicklamprecht** [comment]
Then it can be removed.

**Comment by Ghost-chu** [comment]
` cache data instead of writing each time -> persist every N minutes`
what cache data?

**Comment by Ghost-chu** [comment]
`use PreparedStatement in the right way`
Actually, i not be good at for SQL...

**Comment by Ghost-chu** [comment]
`properly handle configurations` Yes, you are right

**Comment by Ghost-chu** [comment]
I think i need sleep and find another time to continue refactoring.  
00:03 BJT now.

**Comment by yannicklamprecht** [comment]
> `cache data instead of writing each time -> persist every N minutes`
> what cache data?

Here we need to evaluate how frequently the database is accessed and if it is necessary to cache certain data changes to reduce load.


Good night.

**Comment by Ghost-chu** [comment]
Complete `Remove classes that are not used anymore`

**Comment by yannicklamprecht** [comment]
What do you think of that config format?
```
!!org.maxgamer.quickshop.language.Language
command:
  descriptionDebug: '&ePrint debug infomation'
  noTargetGiven: '&cUsage: /qs export mysql|sqlite'
controlpanel:
  empty:
    hover: '&eLooking you want changing shop and click to clear.'
    normal: '&aEmpty: Remove shop all items &e[&d&lOK&e]'
  information: '&aShop Control Panel:'
  modeBuying:
    hover: '&eLooking you want changing shop and click to switch enabled or disabled.'
    normal: '&aShop mode: &bBuying &e[&d&lSwitch&e]'
  modeSelling:
    hover: '&eLooking you want changing shop and click to switch enabled or disabled.'
    normal: '&aShop mode: &bSelling &e[&d&lSwitch&e]'
  price:
    hover: '&eLooking you want changing shop and click to set new price.'
    normal: '&aPrice: &b{0} &e[&d&lSet&e]'
  refill:
    hover: '&eLooking you want changing shop and click to refill.'
    normal: '&aRefill: Refill the shop items &e[&d&lOK&e]'
  remove:
    hover: '&eClick to remove this shop.'
    normal: '&c&l[Remove Shop]'
  setOwner:
    hover: '&eLooking you want changing shop and click to switch owner.'
    normal: '&aOwner: &b{0} &e[&d&lChange&e]'
  sign:
    owner:
      line1: ''
      line2: Enter
      line3: new owner name
      line4: at first line
    price:
      line1: ''
      line2: Enter
      line3: new shop price
      line4: at first line
    refill:
      line1: ''
      line2: Enter amount
      line3: you want fill
      line4: at first line
  unlimited:
    hover: '&eLooking you want changing shop and click to switch enabled or disabled.'
    normal: '&aUnlimited: {0} &e[&d&lSwitch&e]'
language:
  contributors: [
    ]
  country: England
  version: 1
languageVersion: 2
shopDoesNotExist: '&cThere had no shop.'
sign:
  owner:
    line1: ''
    line2: Enter
    line3: new owner name
    line4: at first line
  price:
    line1: ''
    line2: Enter
    line3: new shop price
    line4: at first line
  refill:
    line1: ''
    line2: Enter amount
    line3: you want fill
    line4: at first line
signsUlimited: Unlimited
```
