### ISSUE TITLE
[BUG] Players getting message "Intergration Worldguard denied the Shop Trading".

### ISSUE THREAD

**Issue by PhantumOne** [Ghost-chu/QuickShop-Reremake#454]
**Describe the bug**
I created an Admin Claim on my Server then I setup a single chest and hit it with an item.
I the entered the price of the item to sell and it placed a sale sign on the chest. I then left click the sign and entered amount in chat and it gave me the item. So I setup another 265 chest and then set all of them to Unlimited. When any of the OP's use them they get the item but when a player clicks it, it ask for amount to buy and the player types in 1 in chat and they get this message "Intergation Worldguard denied the Shop Trading". No error messages show up in the server console.

I went to Worldguard Discord page and asked them if I was needing to set a Flag and they told me it was a plugin issue.  I looked through all your docs and FAQ's as well as reading all the Open and closed issues on Github and could not find anything.

All players have: quckshop.use and quickshop.preview permission so the can use the shop and the [Item Preview] in chat. But if the OP's can use it, then it has to be a permission issue and I don't know what other permission to give. I only use it for Admin Shops not player shops.

**To Reproduce**
1. Created Admin Claim
2. Created Admin Shop (placed a chest, hit it with item, put in price, sign appeared, typed "/qs unlimited" and sign changed to AdminShop on first line of sign and Selling Unlimited on the second line.)
3. I clicked on the sign and entered 1 into chat and it gave me the item.
4. I then removed my op status and as a player, I clicked the sigh and entered 1 into chat and the message appears. 

**Expected behavior**
I expected the Players to get an item, not a message.

**Screenshots**
![2020-05-07_11 29 28](https://user-images.githubusercontent.com/29824904/81320287-8f100380-9056-11ea-9be5-ebcd55042aa3.png)
![2020-05-07_11 29 46](https://user-images.githubusercontent.com/29824904/81320357-aea72c00-9056-11ea-8171-6a5d549ebeb8.png)
![2020-05-07_11 29 54](https://user-images.githubusercontent.com/29824904/81320364-b1a21c80-9056-11ea-96be-2ffd1d54a24f.png)
![2020-05-07_11 30 02](https://user-images.githubusercontent.com/29824904/81320370-b36be000-9056-11ea-831f-4dfa32d0ca58.png)
![2020-05-07_11 30 28](https://user-images.githubusercontent.com/29824904/81320373-b5ce3a00-9056-11ea-9c20-a571a50afdfd.png)
![2020-05-07_11 30 38](https://user-images.githubusercontent.com/29824904/81320382-b8c92a80-9056-11ea-856f-754f3b74e267.png)
![2020-05-07_11 30 58](https://user-images.githubusercontent.com/29824904/81320392-bbc41b00-9056-11ea-809d-da08873ce7a5.png)
![2020-05-07_11 31 13](https://user-images.githubusercontent.com/29824904/81320396-bd8dde80-9056-11ea-8181-d5f0c03efdff.png)
![2020-05-07_11 31 20](https://user-images.githubusercontent.com/29824904/81320403-bff03880-9056-11ea-9cf2-c8851716f6ef.png)
![2020-05-07_11 31 28](https://user-images.githubusercontent.com/29824904/81320408-c1b9fc00-9056-11ea-8432-3714dfa9f5fc.png)
![qd01](https://user-images.githubusercontent.com/29824904/81320525-f1690400-9056-11ea-9b6a-00ab00fccfef.png)

**Paste link:**
 Execute command /qs paste, you will get a link contains your server information, paste it under this text.
 You must create a paste, except plugin completely won't work.
 If you create failed, you should find a paste file under the plugin/QuickShop folder.

https://paste.enginehub.org/GntJaEn4S

**Additional context**

**Comment by sandtechnology** [comment]
Is the shop is in the Worldguard area? if not, you need to disable white-list mode in there:
```
  worldguard:
    enable: true
    whitelist-mode: true
    create:
    - FLAG
    - CHEST_ACCESS
    trade: []
```

**Comment by sandtechnology** [comment]
Also you need to restart to make flag change take effected(example.config.yml):
```
#WorldGuard Integration Component
  #CHANGE NEEDS RESTART THE SERVER
  #CHANGE NEEDS RESTART THE SERVER
  #CHANGE NEEDS RESTART THE SERVER
  worldguard:
    enable: false
    whitelist-mode: true
      #Player if want create a shop, player must pass which checks?
      #You can use multi checks in same time.
      #Priority: UP to DOWN
      #
    #Avaliable field:
    #FLAG = Region must set quickshop-create flag available for players.
    #BUILD = Player must have ability to build at the target region.
    #CHEST_ACCESS = Player must can access chest.
    #INTERACT = Player must have ability to interact in the target region.
    create:
      - FLAG
      - CHEST_ACCESS
        #Player if want create a shop, player must pass which checks?
        #You can use multi checks in same time.
        #Priority: UP to DOWN
        #
        #Avaliable field:
      #FLAG = Region must set quickshop-trade flag available for players.
      #BUILD = Player must have ability to build at the target region.
      #CHEST_ACCESS = Player must can access chest.
      #INTERACT = Player must have ability to interact in the target region.
    trade: []
```
