### ISSUE TITLE
[BUG] Plug is ignoring  repaircost: false

### ISSUE THREAD

**Issue by Nextopi** [Ghost-chu/QuickShop-Reremake#461]
**Describe the bug**
Items with different repair cost cannot be sold

**To Reproduce**

Sell 2 items with similar enchant but different repair cost

**The items**

```
item:
  ==: org.bukkit.inventory.ItemStack
  v: 2230
  type: BOW
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    enchants:
      ARROW_FIRE: 1
      ARROW_INFINITE: 1
      ARROW_DAMAGE: 5
      ARROW_KNOCKBACK: 2
      DURABILITY: 3
    repair-cost: 7
```
```

item:
  ==: org.bukkit.inventory.ItemStack
  v: 2230
  type: BOW
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    enchants:
      ARROW_FIRE: 1
      ARROW_INFINITE: 1
      ARROW_DAMAGE: 5
      ARROW_KNOCKBACK: 2
      DURABILITY: 3
    repair-cost: 31

```
