### ISSUE TITLE
[BUG] Shops are disappearing

### ISSUE THREAD

**Issue by KeyArch** [Ghost-chu/QuickShop-Reremake#538]
Hi, im using quickshop in 2 worlds.  I don't know why shops are disappearing from 1 world when I restart the server. Im using mysql.

CONFIG:
```
# 
# whether to use decimal format output.
config-version: 108
language: en-US
game-language: default
dev-mode: true
tax: 0.0
tax-account: tax
show-tax: false
respect-item-flag: true
log-actions: true
whole-number-prices-only: false
force-bukkit-chat-handler: false
disabled-metrics: false
updater: true
auto-report-errors: true
include-offlineplayer-list: false
economy-type: 0
use-decimal-format: false
decimal-format: '#,###.##'
send-display-item-protection-alert: false
send-shop-protection-alert: false
server-platform: 0
use-caching: false
database:
  mysql: true
  host: localhost
  port: 3306
  database: [DELETED]
  user: [DELETED]
  password: [DELETED]
  prefix: none
  usessl: false
  queue: false
  queue-commit-interval: 2
  auto-fix-encoding-issue-in-database: false
limits:
  use: false
  default: 10
  old-algorithm: false
  ranks:
    quickshop:
      vip: 20
shop-blocks:
- CHEST
- TRAPPED_CHEST
- ENDER_CHEST
shop:
  cost: 0
  refund: false
  disable-creative-mode-trading: false
  disable-super-tool: false
  allow-owner-break-shop-sign: false
  price-change-requires-fee: true
  fee-for-price-change: 0
  lock: true
  disable-quick-create: false
  interact:
    switch-mode: false
    sneak-to-create: false
    sneak-to-trade: false
    sneak-to-control: false
  auto-sign: true
  pay-unlimited-shop-owners: false
  display-items: true
  display-items-check-ticks: 6000
  display-type: 2
  display-auto-despawn: false
  display-despawn-range: 20
  display-check-time: 40
  display-allow-stacks: false
  enchance-display-protect: false
  enchance-shop-protect: false
  find-distance: 45
  alternate-currency-symbol: $
  disable-vault-format: false
  currency-symbol-on-right: false
  ignore-unlimited-shop-messages: false
  auto-fetch-shop-messages: true
  ignore-cancel-chat-event: false
  allow-shop-without-space-for-sign: false
  minimum-price: 0.01
  maximum-price: -1
  price-restriction: []
  maximum-digits-in-price: -1
  show-owner-uuid-in-controlpanel-if-op: false
  sign-material: OAK_WALL_SIGN
  use-enchantment-for-enchanted-book: false
  blacklist-world:
  - disabled_world_name
  blacklist-lores:
  - SoulBound
  protection-checking: true
  max-shops-checks-in-once: 100
  display-item-use-name: false
  update-sign-when-inventory-moving: true
  allow-economy-loan: false
  word-for-trade-all-items: all
  allow-free-shop: false
  use-fast-shop-search-algorithm: true
  ongoing-fee:
    enable: false
    ticks: 42000
    cost-per-shop: 2
    ignore-unlimited: true
  force-load-downgrade-items:
    enable: false
    method: 0
  remove-protection-trigger: true
  allow-stacks: false
blacklist:
- Bedrock
lockette:
  enable: true
  private: '[Private]'
  more_users: '[More Users]'
plugin:
  Multiverse-Core: true
  OpenInv: true
  PlaceHolderAPI: true
  LWC: true
  BlockHub:
    enable: true
    only: false
effect:
  sound:
    ontabcomplete: true
    oncommand: true
    onclick: true
matcher:
  work-type: 1
  item:
    damage: true
    repaircost: false
    displayname: true
    lores: true
    enchs: true
    potions: true
    attributes: true
    itemflags: true
    custommodeldata: true
    books: true
    banner: true
    skull: true
    firework: true
    map: true
    leatherArmor: true
    fishBucket: true
    suspiciousStew: true
    shulkerBox: true
mixedeconomy:
  deposit: eco give {0} {1}
  withdraw: eco take {0} {1}
integration:
  towny:
    enable: false
    ignore-disabled-worlds: true
    create:
    - SHOPTYPE
    - MODIFY
    trade: []
  worldguard:
    enable: false
    whitelist-mode: false
    create:
    - FLAG
    - CHEST_ACCESS
    trade: []
  plotsquared:
    enable: false
    whitelist-mode: true
  lands:
    enable: false
    whitelist-mode: false
    ignore-disabled-worlds: true
  residence:
    enable: false
    whitelist-mode: true
    create:
    - FLAG
    - interact
    - use
    trade: []
  factions:
    enable: false
    whitelist-mode: true
    create:
      require:
        open: false
        normal: true
        wilderness: false
        peaceful: true
        permanent: false
        safezone: false
        own: false
        warzone: false
      flags:
      - CONTAINER
      - ECONOMY
    trade:
      require:
        open: false
        normal: true
        wilderness: false
        peaceful: false
        permanent: false
        safezone: false
        own: false
        warzone: false
      flags: []
protect:
  explode: true
  hopper: true
  entity: true
custom-item-stacksize: []
server-uuid: b6e9642d-5d6b-4fdd-90d3-73a43854d5c2
```
