### ISSUE TITLE
[BUG] Color formatting not working on signs

### ISSUE THREAD

**Issue by Kamology** [Ghost-chu/QuickShop-Reremake#577]
**Describe the bug**
I reported this in the Discord but figured I'd put it formally here too; Whenever I create a shop, the color formatting before the name (&c) doesn't turn into a color. I tried outright removing the &c from the json file too and it didn't seem to reflect that change either but that's kind of besides the point.

**To Reproduce**
Simply create a chest shop by left clicking with an item and entering its price.

**Expected behavior**
The color code &c will properly convert into a red colored name.

**Screenshots**
![image](https://user-images.githubusercontent.com/65583898/94397278-5a413d80-0118-11eb-9ad5-b545dec09e00.png)

**Paste link:**
 Execute command /qs paste, you will get a link contains your server information, paste it under this text.
 You must create a paste, except plugin completely won't work.
 If you create failed, you should find a paste file under the plugin/QuickShop folder.

- https://paste.enginehub.org/NabiDAeBB

**Additional context**
N/A

**Comment by Ghost-chu** [comment]
config.yml broken, please delete it and let plugin re-create new one.

**Comment by Kamology** [comment]
Oh my bad I forgot to mention I did that to no avail lol. Here's an updated paste after the fact to see if it gives any new info. 

https://paste.enginehub.org/qOAOsYtRl

**Comment by sandtechnology** [comment]
```
Configurations:
	*********************************
	config.yml:
		
# 
# whether to use decimal format output.
shop: {}
logging: {}
integration:
  worldguard: {}
matcher:
  work-type: 0
server-uuid: 19d150ec-645e-4b4a-8ecd-41abe91bab88
```
Still broken, please make sure you have download the full jar, it may be is broken.
