### ISSUE TITLE
[BUG] Error in formatting the left line of tableformat.

### ISSUE THREAD

**Issue by SrBedrock** [Ghost-chu/QuickShop-Reremake#747]
## **Describe the bug**
Error in formatting the left line of `tableformat`.
 
## **To Reproduce**

1. Right click on the store that sells books.

## **Expected behavior**

Dark purple line without the name `dark_purple`.

## **Screenshots**

Error in formatting the left line:
![image](https://user-images.githubusercontent.com/51332006/101994289-1930e200-3ca0-11eb-8afd-2d293cf3f031.png)

## **Paste link:**

- https://gist.github.com/SrBedrock/cf3fd39c5046f516c0f2ddc7c5812219

## **Additional context**

config:
```yml
  "tableformat": {
    "left_half_line": "&m                    &r ",
    "right_half_line": " &m                    &r",
    "full_line": "&m                                   &r",
    "left_begin": "| "
```
