### ISSUE TITLE
Allow more towny options 

### ISSUE THREAD

**Issue by RSNFreud** [Ghost-chu/QuickShop-Reremake#764]
Allow you to allow creating shops in other towny plot types in the config

**Comment by Ghost-chu** [comment]
```YAML
  #Towny Integration Component
  towny:
    enable: false
    #If ignore disabled world checking
    ignore-disabled-worlds: true
    #If a player want to create a shop, player must pass which checks?
    #You can use multi checks in same time.
    #Priority: UP to DOWN.
    #
    #Avaliable field:
    #OWN = Player must create the shop on their plot.
    #MODIFY = Player must have ability to build at the target plot.
    #SHOPTYPE = Player must create the shop on SHOP type plot.
    create:
      - SHOPTYPE
      - MODIFY
    #If a player want to trade with the shop, player must pass which checks?
    #You can use multi checks in same time.
    #Priority: UP to DOWN.
    #
    #Avaliable field:
    #OWN = Player must create the shop on their plot.
    #MODIFY = Player must have ability to build at the target plot.
    #SHOPTYPE = Player must create the shop on SHOP type plot.
    trade: []
    delete-shop-on-resident-leave: false

```
Pretty sure remove `- SHOPTYPE` will allow player creating shops in non-shop type plot.
