### ISSUE TITLE
[Feature] Allow breaking shop containers when multiple click events occur in succession.

### ISSUE THREAD

**Issue by mibby** [Ghost-chu/QuickShop-Reremake#812]
**Describe the Feature**
Would it be possible to allow players to break allowed shop-configured containers when they have an item in their hand and are trying to break the container instead of creating a shop? When you hold left click with an item (trying to break a chest for example), QuickShop detects it as left clicking to create a shop.

Is it possible to only listen for 1 click event to create a shop and if multiple come in, don't? 

**Additional context**
Had someone complain about this annoyance to destroy chests with an item in hand because they can't send a message after, as it thinks they are creating a shop.

**Comment by Ghost-chu** [comment]
You can ignore that message and keeping destory block.
Minecraft also send one-click event when player diging block.
To prevent spam message send to player when destorying shop, try enable sneak-create feature.



---Original---

**Comment by mibby** [comment]
Thanks! ``sneak-to-create`` works great and is a perfect workaround to this problem.

I did run across one issue. ``sneak-to-trade`` & ``sneak-to-control`` didn't seem to work. I was able to left click buy & right click my shop sign to open the control menu instead of it being ``shift+click``.

**Comment by Ghost-chu** [comment]
```yaml
  #Interact options
  interact:
    #Interact mode
    #0=Only mode, Only can interact with sneak or normal interact
    #1=Both mode, interact with sneak (if enabled) and normal interact will do
    #2=Reversed mode, disable interact with sneak if you enable blow option
    interact-mode: 0
    sneak-to-create: false
    sneak-to-trade: false
    sneak-to-control: false
```
Well, you may need to set `interact-mode` also.
But I'm not clearly know how it works. maybe @sandtechnology will told you :)
