### ISSUE TITLE
[Feature] Remove shops which owner haven't played for x days

### ISSUE THREAD

**Issue by sandtechnology** [Ghost-chu/QuickShop-Reremake#912]
Taken from @ ThiagoROX which in discord
I don't think that command would be a good way, I believe it would be better when the option is enabled, the plugin will perform the check when it is initialized (server initialization) and remove the stores, so we wouldn't have a performance problem and so on...

```
Exemple:
purge:
  # Should it be enabled?
  enabled: false
  # How many days should a player be offline for?
  time: 30
```
At each startup the plugin checks when the player who owns any store last logged in and if he has not logged in for x days, remove all of his stores.
Command could be added as well, but I think that at startup it is more convenient for server administrators, we all restart the server at least once a week
